GENERIC_RULES = [
    {
        "id": "GEN001",
        "name": "Hardcoded API Key",
        "pattern": r'(?i)(api[_\-]?key|apikey|api[_\-]?secret|access[_\-]?key)\s*[=:]\s*["\'][A-Za-z0-9_\-]{16,}["\']',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-798",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Hardcoded API keys embedded in source code are exposed if the repository is shared or made public.",
        "recommendation": "Store secrets in environment variables or a dedicated secrets manager (e.g., HashiCorp Vault, AWS Secrets Manager). Never commit secrets to version control.",
    },
    {
        "id": "GEN002",
        "name": "Hardcoded Password",
        "pattern": r'(?i)(password|passwd|pwd|secret|passphrase)\s*[=:]\s*["\'][^"\']{4,}["\']',
        "severity": "Critical",
        "confidence": "Medium",
        "cwe": "CWE-259",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Hardcoded passwords can be extracted by anyone with access to the source code.",
        "recommendation": "Use environment variables or secret management systems. Never hardcode credentials.",
    },
    {
        "id": "GEN003",
        "name": "Hardcoded Token / Bearer Secret",
        "pattern": r'(?i)(token|bearer|auth[_\-]?token|jwt[_\-]?secret|secret[_\-]?key)\s*[=:]\s*["\'][A-Za-z0-9_\-\.]{16,}["\']',
        "severity": "Critical",
        "confidence": "Medium",
        "cwe": "CWE-798",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Tokens and secrets embedded in code can be extracted and used for unauthorized access.",
        "recommendation": "Load tokens from environment variables at runtime. Use token rotation and expiration policies.",
    },
    {
        "id": "GEN004",
        "name": "Weak Cryptography - MD5",
        "pattern": r'(?i)\bmd5\b',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-327",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "MD5 is cryptographically broken and should not be used for security-sensitive operations like password hashing.",
        "recommendation": "Use bcrypt, argon2, or scrypt for password hashing. Use SHA-256 or SHA-3 for integrity checks.",
    },
    {
        "id": "GEN005",
        "name": "Weak Cryptography - SHA1",
        "pattern": r'(?i)\bsha[-_]?1\b|hashlib\.sha1|SHA1\(',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-327",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "SHA-1 is considered weak and vulnerable to collision attacks.",
        "recommendation": "Replace SHA-1 with SHA-256 or SHA-3 for security-sensitive operations.",
    },
    {
        "id": "GEN006",
        "name": "Sensitive Data in URL",
        "pattern": r'(?i)(https?://[^\s]*[?&](password|passwd|pwd|secret|token|api[_\-]?key)=)',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-598",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Sensitive data in URLs can be logged in server logs, browser history, and referrer headers.",
        "recommendation": "Pass sensitive data in request headers or request body instead of URL query parameters.",
    },
    {
        "id": "GEN007",
        "name": "Insecure CORS - Wildcard",
        "pattern": r'(?i)(Access-Control-Allow-Origin|cors.*origin)\s*[=:]\s*["\']?\*["\']?',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-942",
        "owasp": "A05:2021 - Security Misconfiguration",
        "explanation": "Wildcard CORS allows any origin to make cross-origin requests, enabling CSRF and data theft.",
        "recommendation": "Restrict CORS to specific trusted origins. Avoid using '*' for authenticated endpoints.",
    },
    {
        "id": "GEN008",
        "name": "Debug Mode Enabled",
        "pattern": r'(?i)(debug\s*[=:]\s*(true|1|on)|app\.run\(.*debug\s*=\s*True)',
        "severity": "Medium",
        "confidence": "High",
        "cwe": "CWE-94",
        "owasp": "A05:2021 - Security Misconfiguration",
        "explanation": "Debug mode in production exposes stack traces, internal paths, and sensitive configuration.",
        "recommendation": "Disable debug mode in production. Use environment-based configuration to control debug settings.",
    },
    {
        "id": "GEN009",
        "name": "Unsafe eval() Usage",
        "pattern": r'\beval\s*\(',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-95",
        "owasp": "A03:2021 - Injection",
        "explanation": "eval() executes arbitrary code and is highly dangerous when used with user-controlled input.",
        "recommendation": "Avoid eval() entirely. Use safe alternatives like JSON.parse() for data parsing or ast.literal_eval() for Python.",
    },
    {
        "id": "GEN010",
        "name": "SQL Injection - String Concatenation",
        "pattern": r'(?i)(SELECT|INSERT|UPDATE|DELETE|DROP|UNION)\s+.*["\'\s]\s*\+\s*[\w\$]',
        "severity": "Critical",
        "confidence": "Medium",
        "cwe": "CWE-89",
        "owasp": "A03:2021 - Injection",
        "explanation": "String concatenation in SQL queries allows attackers to inject malicious SQL code.",
        "recommendation": "Use parameterized queries or prepared statements. Never concatenate user input into SQL strings.",
    },
    {
        "id": "GEN011",
        "name": "Private Key / Certificate Exposure",
        "pattern": r'-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-321",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Private keys embedded in source code can be extracted and used to compromise security.",
        "recommendation": "Never store private keys in source code. Use key management services or environment-based secrets.",
    },
    {
        "id": "GEN012",
        "name": "Open Redirect",
        "pattern": r'(?i)(redirect|location)\s*[=\(]\s*[^\n]*request\.(get|args|params|query)',
        "severity": "Medium",
        "confidence": "Medium",
        "cwe": "CWE-601",
        "owasp": "A01:2021 - Broken Access Control",
        "explanation": "Open redirects allow attackers to redirect users to malicious sites via a trusted URL.",
        "recommendation": "Validate redirect URLs against a whitelist of allowed domains. Reject absolute URLs from user input.",
    },
]
