HTML_RULES = [
    {
        "id": "HTML001",
        "name": "Inline JavaScript - Potential XSS",
        "pattern": r'<script[^>]*>(?!.*src)[^<]*</script>',
        "severity": "Medium",
        "confidence": "Low",
        "cwe": "CWE-79",
        "owasp": "A03:2021 - Injection",
        "explanation": "Inline scripts bypass Content Security Policy (CSP) nonce-based protections if not properly controlled.",
        "recommendation": "Move scripts to external files and configure CSP with strict-dynamic or nonces to prevent unauthorized script execution.",
    },
    {
        "id": "HTML002",
        "name": "Form Without CSRF Protection",
        "pattern": r'<form[^>]*method=["\']post["\'][^>]*>(?!.*csrf)',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-352",
        "owasp": "A01:2021 - Broken Access Control",
        "explanation": "HTML forms using POST without CSRF tokens are vulnerable to Cross-Site Request Forgery attacks.",
        "recommendation": "Include a CSRF token in all POST forms. Validate the token server-side on every state-changing request.",
    },
    {
        "id": "HTML003",
        "name": "External Script Without Subresource Integrity",
        "pattern": r'<script[^>]+src=["\'][https?://][^"\']+["\'](?![^>]*integrity)',
        "severity": "Medium",
        "confidence": "High",
        "cwe": "CWE-353",
        "owasp": "A08:2021 - Software and Data Integrity Failures",
        "explanation": "Loading scripts from external CDNs without SRI allows supply chain attacks if the CDN is compromised.",
        "recommendation": "Add integrity attribute with hash: <script src='...' integrity='sha384-...' crossorigin='anonymous'>",
    },
    {
        "id": "HTML004",
        "name": "Autocomplete Enabled on Password Field",
        "pattern": r'<input[^>]*type=["\']password["\'][^>]*(?!autocomplete=["\']off["\'])',
        "severity": "Low",
        "confidence": "Medium",
        "cwe": "CWE-257",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Browser autocomplete on password fields can lead to credential leakage on shared devices.",
        "recommendation": "Add autocomplete='off' to sensitive input fields on shared or kiosk systems.",
    },
    {
        "id": "HTML005",
        "name": "Missing X-Frame-Options / Clickjacking Risk",
        "pattern": r'(?i)<iframe[^>]*src=["\'][^"\']*["\']',
        "severity": "Medium",
        "confidence": "Low",
        "cwe": "CWE-1021",
        "owasp": "A05:2021 - Security Misconfiguration",
        "explanation": "Pages framed within iframes can be used for clickjacking attacks.",
        "recommendation": "Set the X-Frame-Options: DENY or SAMEORIGIN header, or use CSP frame-ancestors directive.",
    },
    {
        "id": "HTML006",
        "name": "javascript: Protocol in href",
        "pattern": r'href\s*=\s*["\']javascript:',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-79",
        "owasp": "A03:2021 - Injection",
        "explanation": "The javascript: protocol in href attributes can execute scripts and is a common XSS vector.",
        "recommendation": "Use onclick event handlers with proper sanitization instead of javascript: in href attributes.",
    },
    {
        "id": "HTML007",
        "name": "Missing Content Security Policy Meta Tag",
        "pattern": r'<meta[^>]*http-equiv=["\']Content-Security-Policy["\']',
        "severity": "Low",
        "confidence": "Low",
        "cwe": "CWE-1021",
        "owasp": "A05:2021 - Security Misconfiguration",
        "explanation": "Absence of Content Security Policy allows unrestricted script sources and XSS risk.",
        "recommendation": "Define a strict CSP via HTTP header: Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-...'",
    },
    {
        "id": "HTML008",
        "name": "Sensitive Data in HTML Comment",
        "pattern": r'<!--.*(?i)(password|api[_\-]?key|secret|token|credential).*-->',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-615",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Sensitive information in HTML comments is visible to any user who views the page source.",
        "recommendation": "Remove all sensitive data from HTML comments. Use server-side variables for sensitive configuration.",
    },
]
