JAVASCRIPT_RULES = [
    {
        "id": "JS001",
        "name": "Cross-Site Scripting - innerHTML",
        "pattern": r'\.innerHTML\s*[+]?=',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-79",
        "owasp": "A03:2021 - Injection",
        "explanation": "Setting innerHTML with unsanitized data allows attackers to inject and execute malicious scripts.",
        "recommendation": "Use textContent or innerText for plain text. If HTML is needed, use DOMPurify to sanitize first.",
    },
    {
        "id": "JS002",
        "name": "Cross-Site Scripting - document.write",
        "pattern": r'document\.write\s*\(',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-79",
        "owasp": "A03:2021 - Injection",
        "explanation": "document.write() with user-controlled data enables XSS attacks.",
        "recommendation": "Replace document.write() with DOM manipulation methods like createElement() and appendChild().",
    },
    {
        "id": "JS003",
        "name": "Cross-Site Scripting - dangerouslySetInnerHTML",
        "pattern": r'dangerouslySetInnerHTML\s*=',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-79",
        "owasp": "A03:2021 - Injection",
        "explanation": "dangerouslySetInnerHTML bypasses React's XSS protections and can enable script injection.",
        "recommendation": "Sanitize content with DOMPurify before using dangerouslySetInnerHTML, or redesign to avoid it entirely.",
    },
    {
        "id": "JS004",
        "name": "Unsafe eval() Usage",
        "pattern": r'\beval\s*\(',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-95",
        "owasp": "A03:2021 - Injection",
        "explanation": "eval() executes arbitrary JavaScript code and is dangerous with user-controlled input.",
        "recommendation": "Replace eval() with JSON.parse() for data, or use safer alternatives. Enable CSP to block unsafe-eval.",
    },
    {
        "id": "JS005",
        "name": "Command Injection - child_process",
        "pattern": r'require\s*\(\s*["\']child_process["\']\s*\)|child_process\.(exec|execSync|spawn)\s*\(',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-78",
        "owasp": "A03:2021 - Injection",
        "explanation": "Executing shell commands with user-controlled input enables command injection attacks.",
        "recommendation": "Use execFile() with a fixed executable path and pass arguments as an array, not via shell string.",
    },
    {
        "id": "JS006",
        "name": "SQL Injection - String Concatenation",
        "pattern": r'(?i)(query|execute)\s*\(\s*["`\'](SELECT|INSERT|UPDATE|DELETE|DROP).*\+',
        "severity": "Critical",
        "confidence": "Medium",
        "cwe": "CWE-89",
        "owasp": "A03:2021 - Injection",
        "explanation": "Concatenating user input into SQL query strings allows SQL injection attacks.",
        "recommendation": "Use parameterized queries or prepared statements with your database library (e.g., node-postgres, mysql2).",
    },
    {
        "id": "JS007",
        "name": "Prototype Pollution",
        "pattern": r'(?i)(__proto__|prototype\s*\[|Object\.assign\s*\(\s*\{\s*\})',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-1321",
        "owasp": "A03:2021 - Injection",
        "explanation": "Prototype pollution allows attackers to modify JavaScript object prototypes, affecting all objects.",
        "recommendation": "Use Object.create(null) for untrusted data, validate object keys, or use Map instead of plain objects.",
    },
    {
        "id": "JS008",
        "name": "Insecure Local Storage for Sensitive Data",
        "pattern": r'localStorage\.(setItem|getItem)\s*\(',
        "severity": "Medium",
        "confidence": "Medium",
        "cwe": "CWE-922",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "LocalStorage is accessible to any JavaScript on the page; storing tokens/secrets there risks XSS theft.",
        "recommendation": "Store authentication tokens in httpOnly cookies. Avoid storing sensitive data in localStorage.",
    },
    {
        "id": "JS009",
        "name": "Insecure Redirect - location.href",
        "pattern": r'(?i)(location\.href|window\.location)\s*=.*request|param|query|url',
        "severity": "Medium",
        "confidence": "Medium",
        "cwe": "CWE-601",
        "owasp": "A01:2021 - Broken Access Control",
        "explanation": "Redirecting to user-supplied URLs enables open redirect attacks for phishing.",
        "recommendation": "Validate redirect URLs against a strict whitelist of allowed destinations.",
    },
    {
        "id": "JS010",
        "name": "Hardcoded JWT Secret",
        "pattern": r'(?i)(jwt\.sign|jsonwebtoken)\s*\(.*["\'][A-Za-z0-9_\-\.]{8,}["\']',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-798",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "A hardcoded JWT secret allows attackers to forge valid tokens for any user.",
        "recommendation": "Load JWT secrets from environment variables. Use asymmetric keys (RS256) for distributed systems.",
    },
    {
        "id": "JS011",
        "name": "NoSQL Injection",
        "pattern": r'(?i)(find|findOne|update|delete)\s*\(\s*\{.*req\.(body|query|params)',
        "severity": "Critical",
        "confidence": "Medium",
        "cwe": "CWE-943",
        "owasp": "A03:2021 - Injection",
        "explanation": "Passing user input directly into MongoDB queries can allow NoSQL injection attacks.",
        "recommendation": "Validate and sanitize input. Use mongoose schemas with strict validation. Avoid passing raw user objects to queries.",
    },
    {
        "id": "JS012",
        "name": "Cross-Site Scripting - outerHTML",
        "pattern": r'\.outerHTML\s*[+]?=',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-79",
        "owasp": "A03:2021 - Injection",
        "explanation": "Setting outerHTML with user-supplied data allows XSS attacks.",
        "recommendation": "Sanitize HTML content with DOMPurify before assigning to outerHTML.",
    },
    {
        "id": "JS013",
        "name": "Insecure Cookie - Missing httpOnly/Secure",
        "pattern": r'(?i)document\.cookie\s*=|res\.cookie\s*\(',
        "severity": "Medium",
        "confidence": "Medium",
        "cwe": "CWE-1004",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Cookies set without httpOnly and Secure flags are vulnerable to XSS theft and interception.",
        "recommendation": "Always set cookies with httpOnly=true, Secure=true, and SameSite=Strict attributes.",
    },
    {
        "id": "JS014",
        "name": "Path Traversal in Node.js",
        "pattern": r'(?i)(fs\.(readFile|readFileSync|createReadStream))\s*\(.*req\.(body|query|params)',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-22",
        "owasp": "A01:2021 - Broken Access Control",
        "explanation": "Reading files with user-supplied paths allows attackers to traverse directories and read sensitive files.",
        "recommendation": "Resolve paths with path.resolve() and verify they stay within the allowed directory.",
    },
]
