JAVA_RULES = [
    {
        "id": "JAVA001",
        "name": "SQL Injection - String Concatenation in Query",
        "pattern": r'(?i)(Statement|createStatement|executeQuery|executeUpdate)\s*.*["\'\s]\+\s*\w',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-89",
        "owasp": "A03:2021 - Injection",
        "explanation": "Concatenating variables into SQL statements allows SQL injection attacks.",
        "recommendation": "Use PreparedStatement with parameterized queries: pstmt = conn.prepareStatement('SELECT * FROM users WHERE id = ?'); pstmt.setInt(1, userId);",
    },
    {
        "id": "JAVA002",
        "name": "XML External Entity (XXE)",
        "pattern": r'(?i)(DocumentBuilderFactory|SAXParserFactory|XMLInputFactory)\.newInstance\s*\(',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-611",
        "owasp": "A05:2021 - Security Misconfiguration",
        "explanation": "Java XML parsers by default process external entity references, enabling XXE attacks.",
        "recommendation": "Disable external entities: factory.setFeature('http://xml.org/sax/features/external-general-entities', false);",
    },
    {
        "id": "JAVA003",
        "name": "Insecure Deserialization - ObjectInputStream",
        "pattern": r'\bObjectInputStream\b.*readObject\s*\(\)',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-502",
        "owasp": "A08:2021 - Software and Data Integrity Failures",
        "explanation": "Java deserialization via ObjectInputStream can execute arbitrary code through gadget chains.",
        "recommendation": "Avoid Java serialization for untrusted data. Use JSON or XML. If serialization is needed, implement a whitelist ObjectInputFilter.",
    },
    {
        "id": "JAVA004",
        "name": "Command Injection - Runtime.exec",
        "pattern": r'Runtime\.getRuntime\s*\(\s*\)\.exec\s*\(',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-78",
        "owasp": "A03:2021 - Injection",
        "explanation": "Runtime.exec() with user-controlled input allows OS command injection.",
        "recommendation": "Pass commands as a String array to avoid shell interpretation. Validate and sanitize all user inputs used in commands.",
    },
    {
        "id": "JAVA005",
        "name": "Path Traversal",
        "pattern": r'(?i)(new\s+File|Paths\.get|FileInputStream)\s*\(.*request\.(getParameter|getAttribute)',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-22",
        "owasp": "A01:2021 - Broken Access Control",
        "explanation": "Creating file paths from user input allows directory traversal attacks.",
        "recommendation": "Canonicalize the path and verify it starts with the intended base directory: path.toRealPath().startsWith(baseDir)",
    },
    {
        "id": "JAVA006",
        "name": "Weak Cryptography - DES/RC4",
        "pattern": r'(?i)Cipher\.getInstance\s*\(\s*["\']?(DES|RC4|RC2|Blowfish)',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-327",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "DES, RC4, and RC2 are broken cipher algorithms with known practical attacks.",
        "recommendation": "Use AES-256-GCM for symmetric encryption. Use RSA-2048+ or ECDSA for asymmetric operations.",
    },
    {
        "id": "JAVA007",
        "name": "Hardcoded Cryptographic Key",
        "pattern": r'(?i)new\s+(SecretKeySpec|SecretKey)\s*\(\s*["\'][^"\']+["\']\.getBytes',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-321",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Hardcoded encryption keys can be extracted from compiled bytecode.",
        "recommendation": "Load cryptographic keys from a key management system (KMS) or secure configuration at runtime.",
    },
    {
        "id": "JAVA008",
        "name": "XSS - Unescaped Output in Servlet",
        "pattern": r'(?i)(getWriter|PrintWriter).*response\.getParameter\s*\(',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-79",
        "owasp": "A03:2021 - Injection",
        "explanation": "Writing user input directly to HTTP response without encoding enables reflected XSS.",
        "recommendation": "Encode output using OWASP Java Encoder: Encode.forHtml(userInput) before writing to response.",
    },
    {
        "id": "JAVA009",
        "name": "SSRF - URL Connection from User Input",
        "pattern": r'(?i)new\s+URL\s*\(.*request\.getParameter',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-918",
        "owasp": "A10:2021 - Server-Side Request Forgery",
        "explanation": "Creating URL connections from user-supplied URLs enables SSRF attacks against internal services.",
        "recommendation": "Validate URL hostname against a whitelist. Block connections to private IP ranges.",
    },
    {
        "id": "JAVA010",
        "name": "Insecure Random",
        "pattern": r'\bnew\s+Random\s*\(\s*\)',
        "severity": "Medium",
        "confidence": "Medium",
        "cwe": "CWE-338",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "java.util.Random is not cryptographically secure and should not be used for security tokens.",
        "recommendation": "Use java.security.SecureRandom for security-sensitive random number generation.",
    },
]
