PHP_RULES = [
    {
        "id": "PHP001",
        "name": "SQL Injection - Direct $_GET/$_POST in Query",
        "pattern": r'(?i)(mysql_query|mysqli_query|pg_query)\s*\(.*\$_(GET|POST|REQUEST|COOKIE)',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-89",
        "owasp": "A03:2021 - Injection",
        "explanation": "Directly using superglobals in SQL queries allows SQL injection without any sanitization.",
        "recommendation": "Use PDO with prepared statements: $stmt = $pdo->prepare('SELECT * FROM users WHERE id = ?'); $stmt->execute([$_GET['id']]);",
    },
    {
        "id": "PHP002",
        "name": "Cross-Site Scripting - echo without htmlspecialchars",
        "pattern": r'(?i)echo\s+\$_(GET|POST|REQUEST|COOKIE|SERVER)',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-79",
        "owasp": "A03:2021 - Injection",
        "explanation": "Echoing user input directly to HTML output enables reflected XSS attacks.",
        "recommendation": "Always escape output: echo htmlspecialchars($_GET['input'], ENT_QUOTES, 'UTF-8');",
    },
    {
        "id": "PHP003",
        "name": "Command Injection - system()/exec()",
        "pattern": r'(?i)\b(system|exec|shell_exec|passthru|proc_open|popen)\s*\(.*\$_(GET|POST|REQUEST)',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-78",
        "owasp": "A03:2021 - Injection",
        "explanation": "Passing user input to command execution functions allows arbitrary OS command injection.",
        "recommendation": "Avoid system/exec with user input. If necessary, use escapeshellarg() to sanitize inputs.",
    },
    {
        "id": "PHP004",
        "name": "Local/Remote File Inclusion",
        "pattern": r'(?i)(include|require|include_once|require_once)\s*\(\s*\$_(GET|POST|REQUEST)',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-98",
        "owasp": "A03:2021 - Injection",
        "explanation": "Including files based on user input allows Local File Inclusion (LFI) or Remote File Inclusion (RFI).",
        "recommendation": "Use a whitelist of allowed file names. Never pass user input directly to include/require.",
    },
    {
        "id": "PHP005",
        "name": "PHP eval() with User Input",
        "pattern": r'(?i)\beval\s*\(.*\$_(GET|POST|REQUEST)',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-95",
        "owasp": "A03:2021 - Injection",
        "explanation": "eval() with user input executes arbitrary PHP code, giving full server compromise.",
        "recommendation": "Never use eval() with user-supplied data. Redesign the logic to avoid dynamic code execution.",
    },
    {
        "id": "PHP006",
        "name": "Insecure Deserialization - unserialize()",
        "pattern": r'(?i)\bunserialize\s*\(\s*\$_(GET|POST|REQUEST|COOKIE)',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-502",
        "owasp": "A08:2021 - Software and Data Integrity Failures",
        "explanation": "Unserializing user-controlled data can trigger object injection and arbitrary code execution.",
        "recommendation": "Use JSON for data exchange. If serialization is needed, verify data integrity with HMAC before unserializing.",
    },
    {
        "id": "PHP007",
        "name": "Path Traversal",
        "pattern": r'(?i)(file_get_contents|fopen|readfile)\s*\(.*\$_(GET|POST|REQUEST)',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-22",
        "owasp": "A01:2021 - Broken Access Control",
        "explanation": "Opening files with user-supplied paths allows directory traversal to read sensitive files.",
        "recommendation": "Use basename() to strip directory components. Validate paths against an allowed base directory.",
    },
    {
        "id": "PHP008",
        "name": "Weak Password Hashing - md5/sha1",
        "pattern": r'(?i)\b(md5|sha1)\s*\(\s*\$',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-916",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "MD5 and SHA1 are not suitable for password hashing due to their speed and lack of salting.",
        "recommendation": "Use password_hash() with PASSWORD_BCRYPT or PASSWORD_ARGON2ID, and password_verify() to check.",
    },
    {
        "id": "PHP009",
        "name": "XSS via print/printf",
        "pattern": r'(?i)(print|printf)\s*\(.*\$_(GET|POST|REQUEST)',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-79",
        "owasp": "A03:2021 - Injection",
        "explanation": "Printing user input directly to the page enables XSS attacks.",
        "recommendation": "Escape all user output with htmlspecialchars() before printing to HTML context.",
    },
    {
        "id": "PHP010",
        "name": "Open Redirect",
        "pattern": r'(?i)header\s*\(\s*["\']Location:\s*.*\$_(GET|POST|REQUEST)',
        "severity": "Medium",
        "confidence": "High",
        "cwe": "CWE-601",
        "owasp": "A01:2021 - Broken Access Control",
        "explanation": "Redirecting to user-controlled URLs enables phishing via open redirect.",
        "recommendation": "Validate redirect URLs against a whitelist of allowed destinations. Reject absolute URLs from user input.",
    },
    {
        "id": "PHP011",
        "name": "SSRF via file_get_contents",
        "pattern": r'(?i)file_get_contents\s*\(\s*\$_(GET|POST|REQUEST)',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-918",
        "owasp": "A10:2021 - Server-Side Request Forgery",
        "explanation": "Fetching URLs from user input can expose internal services via SSRF.",
        "recommendation": "Validate URLs against a whitelist of allowed hosts. Block internal IP ranges.",
    },
    {
        "id": "PHP012",
        "name": "Insecure File Upload",
        "pattern": r'(?i)move_uploaded_file\s*\(',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-434",
        "owasp": "A04:2021 - Insecure Design",
        "explanation": "File uploads without proper validation can allow uploading of malicious PHP files.",
        "recommendation": "Validate file type by content (MIME sniffing), rename uploads, store outside webroot, and restrict execution permissions.",
    },
]
