PYTHON_RULES = [
    {
        "id": "PY001",
        "name": "SQL Injection via String Formatting",
        "pattern": r'(?i)(execute|executemany)\s*\(\s*[f"\'](SELECT|INSERT|UPDATE|DELETE|DROP|UNION)',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-89",
        "owasp": "A03:2021 - Injection",
        "explanation": "Using f-strings or string formatting to build SQL queries allows SQL injection attacks.",
        "recommendation": "Use parameterized queries: cursor.execute('SELECT * FROM users WHERE id = %s', (user_id,))",
    },
    {
        "id": "PY002",
        "name": "SQL Injection via % Formatting",
        "pattern": r'(?i)(execute|executemany)\s*\(\s*["\'].*(SELECT|INSERT|UPDATE|DELETE)\s.*%\s*[\(\w]',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-89",
        "owasp": "A03:2021 - Injection",
        "explanation": "Using % string formatting to build SQL queries allows SQL injection attacks.",
        "recommendation": "Use parameterized queries with placeholders (%s or ?) instead of string formatting.",
    },
    {
        "id": "PY003",
        "name": "Command Injection - os.system",
        "pattern": r'\bos\.system\s*\(',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-78",
        "owasp": "A03:2021 - Injection",
        "explanation": "os.system() executes shell commands and is vulnerable to command injection when user input is included.",
        "recommendation": "Use subprocess.run() with a list of arguments and shell=False. Validate and sanitize all inputs.",
    },
    {
        "id": "PY004",
        "name": "Command Injection - subprocess shell=True",
        "pattern": r'subprocess\.(run|Popen|call|check_output)\s*\(.*shell\s*=\s*True',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-78",
        "owasp": "A03:2021 - Injection",
        "explanation": "Using shell=True in subprocess calls enables shell injection if user input is part of the command.",
        "recommendation": "Use shell=False and pass arguments as a list: subprocess.run(['ls', '-la'], shell=False)",
    },
    {
        "id": "PY005",
        "name": "Insecure Deserialization - pickle",
        "pattern": r'\bpickle\.(loads?|Unpickler)\s*\(',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-502",
        "owasp": "A08:2021 - Software and Data Integrity Failures",
        "explanation": "pickle.loads() can execute arbitrary code when deserializing malicious data.",
        "recommendation": "Avoid pickle for untrusted data. Use JSON, MessagePack, or other safe serialization formats.",
    },
    {
        "id": "PY006",
        "name": "Path Traversal",
        "pattern": r'(?i)(open|os\.path\.join|os\.listdir)\s*\(.*request\.(get|args|form|json|params)',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-22",
        "owasp": "A01:2021 - Broken Access Control",
        "explanation": "Using user-controlled input in file paths can allow attackers to read or write arbitrary files.",
        "recommendation": "Validate file paths against a whitelist. Use os.path.basename() and restrict access to a safe directory.",
    },
    {
        "id": "PY007",
        "name": "Insecure Random for Security",
        "pattern": r'\brandom\.(random|randint|choice|shuffle|sample)\s*\(',
        "severity": "Medium",
        "confidence": "Medium",
        "cwe": "CWE-338",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "The random module is not cryptographically secure and should not be used for security tokens or keys.",
        "recommendation": "Use secrets.token_hex(), secrets.token_urlsafe(), or os.urandom() for security-sensitive random values.",
    },
    {
        "id": "PY008",
        "name": "Code Injection - exec()",
        "pattern": r'\bexec\s*\(',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-94",
        "owasp": "A03:2021 - Injection",
        "explanation": "exec() executes arbitrary Python code and is extremely dangerous with user-controlled input.",
        "recommendation": "Avoid exec() with user input. If necessary, use restricted sandboxes or code analysis tools.",
    },
    {
        "id": "PY009",
        "name": "SSRF - Unvalidated URL Request",
        "pattern": r'requests\.(get|post|put|delete|head|request)\s*\(.*request\.(get|args|form|json|params)',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-918",
        "owasp": "A10:2021 - Server-Side Request Forgery",
        "explanation": "Making HTTP requests to user-supplied URLs can enable SSRF attacks against internal services.",
        "recommendation": "Validate and whitelist allowed URLs/hosts. Block requests to internal IP ranges (127.x, 10.x, 192.168.x).",
    },
    {
        "id": "PY010",
        "name": "Flask Debug Mode",
        "pattern": r'app\.run\s*\(.*debug\s*=\s*True',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-94",
        "owasp": "A05:2021 - Security Misconfiguration",
        "explanation": "Flask debug mode exposes an interactive debugger that allows arbitrary code execution.",
        "recommendation": "Never run Flask with debug=True in production. Use environment-specific configuration.",
    },
    {
        "id": "PY011",
        "name": "Insecure Deserialization - yaml.load",
        "pattern": r'\byaml\.load\s*\([^,\)]+\)',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-502",
        "owasp": "A08:2021 - Software and Data Integrity Failures",
        "explanation": "yaml.load() with arbitrary input can execute Python code embedded in YAML via !!python/object tags.",
        "recommendation": "Use yaml.safe_load() instead, which only loads basic YAML types without executing code.",
    },
    {
        "id": "PY012",
        "name": "Hardcoded Secret Key in Flask/Django",
        "pattern": r'(?i)SECRET_KEY\s*=\s*["\'][^"\']{4,}["\']',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-798",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Hardcoded SECRET_KEY in configuration files can compromise session security and CSRF protection.",
        "recommendation": "Load SECRET_KEY from environment: os.environ.get('SECRET_KEY'). Use a strong, random key per environment.",
    },
    {
        "id": "PY013",
        "name": "SQL Injection via format()",
        "pattern": r'(?i)(execute|executemany)\s*\(.*\.format\s*\(',
        "severity": "Critical",
        "confidence": "High",
        "cwe": "CWE-89",
        "owasp": "A03:2021 - Injection",
        "explanation": "Using .format() to build SQL queries allows injection of arbitrary SQL code.",
        "recommendation": "Use parameterized queries instead of string formatting for SQL queries.",
    },
    {
        "id": "PY014",
        "name": "Insecure SSL/TLS Verification Disabled",
        "pattern": r'verify\s*=\s*False',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-295",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "Disabling SSL certificate verification allows man-in-the-middle attacks.",
        "recommendation": "Always verify SSL certificates. If using self-signed certs, provide the CA bundle path instead.",
    },
    {
        "id": "PY015",
        "name": "XML External Entity (XXE)",
        "pattern": r'(?i)(etree\.parse|xml\.dom\.minidom\.parse|lxml\.etree)\s*\(',
        "severity": "High",
        "confidence": "Medium",
        "cwe": "CWE-611",
        "owasp": "A05:2021 - Security Misconfiguration",
        "explanation": "XML parsers may process external entity references, enabling file disclosure or SSRF.",
        "recommendation": "Disable external entity processing: use defusedxml library or configure parser to disallow external entities.",
    },
    {
        "id": "PY016",
        "name": "Insecure Hash for Password",
        "pattern": r'hashlib\.(md5|sha1)\s*\(',
        "severity": "High",
        "confidence": "High",
        "cwe": "CWE-916",
        "owasp": "A02:2021 - Cryptographic Failures",
        "explanation": "MD5 and SHA1 are not suitable for password hashing as they are fast and vulnerable to brute force.",
        "recommendation": "Use bcrypt, argon2-cffi, or passlib for password hashing with proper salt and work factor.",
    },
]
