from datetime import datetime
from typing import List, Dict, Any


def generate_html_report(
    findings: List[Dict[str, Any]],
    language: str,
    summary: str = "",
) -> str:
    counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0}
    for f in findings:
        sev = f.get("severity", "Low")
        counts[sev] = counts.get(sev, 0) + 1

    rows = []
    for i, f in enumerate(findings, 1):
        rows.append(
            f"""
            <tr>
                <td>{i}</td>
                <td>{f.get('severity', 'N/A')}</td>
                <td>{f.get('vulnerability_name', 'Unknown')}</td>
                <td>{f.get('affected_line', 'N/A')}</td>
                <td>{f.get('cwe', 'N/A')}</td>
                <td>{f.get('owasp_category', 'N/A')}</td>
                <td>{f.get('detection_source', 'N/A')}</td>
                <td>{f.get('evidence', '')}</td>
            </tr>
            """
        )

    header = f"<h1>CodeVuln Agent Security Report</h1>\n<p>Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>\n<p>Language: {language.title()}</p>"
    if summary:
        header += f"\n<p><strong>Executive Summary:</strong> {summary}</p>"

    html = f"""
    <!DOCTYPE html>
    <html lang=\"en\">
    <head>
      <meta charset=\"utf-8\" />
      <title>CodeVuln Agent Report</title>
      <style>
        body {{ font-family: Arial, sans-serif; background: #111; color: #eee; margin: 0; padding: 24px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
        th, td {{ padding: 10px; border: 1px solid #333; }}
        th {{ background: #222; color: #fff; }}
        tr:nth-child(even) {{ background: #1a1a1a; }}
        .badge {{ padding: 4px 8px; border-radius: 4px; color: #fff; }}
        .Critical {{ background: #c0392b; }}
        .High {{ background: #e67e22; }}
        .Medium {{ background: #f1c40f; color: #111; }}
        .Low {{ background: #2ecc71; }}
      </style>
    </head>
    <body>
      {header}
      <h2>Summary</h2>
      <ul>
        <li>Total findings: {len(findings)}</li>
        <li>Critical: {counts['Critical']}</li>
        <li>High: {counts['High']}</li>
        <li>Medium: {counts['Medium']}</li>
        <li>Low: {counts['Low']}</li>
      </ul>
      <h2>Findings</h2>
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Severity</th>
            <th>Vulnerability</th>
            <th>Line</th>
            <th>CWE</th>
            <th>OWASP</th>
            <th>Source</th>
            <th>Evidence</th>
          </tr>
        </thead>
        <tbody>
          {''.join(rows)}
        </tbody>
      </table>
      <footer style=\"margin-top: 24px; font-size: 0.9rem; color: #bbb;\">Report generated by CodeVuln Agent.</footer>
    </body>
    </html>
    """
    return html
