from datetime import datetime
from typing import List, Dict, Any

# Severity emoji removed to keep reports monochrome


def generate_markdown_report(
    findings: List[Dict[str, Any]],
    language: str,
    summary: str = "",
) -> str:
    counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0}
    for f in findings:
        sev = f.get("severity", "Low")
        counts[sev] = counts.get(sev, 0) + 1

    lines = [
        "# CodeVuln Agent — Security Analysis Report",
        "",
        f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**Language:** {language.title()}  ",
        f"**Total Findings:** {len(findings)}",
        "",
        "> **Disclaimer:** This report is generated by an automated security assistant.",
        "> It may contain false positives or false negatives. Manual review is recommended.",
        "",
        "---",
        "",
        "## Summary",
        "",
    ]

    if summary:
        lines += [summary, ""]

    lines += [
        "| Severity | Count |",
        "|----------|-------|",
    ]
    for sev in ["Critical", "High", "Medium", "Low"]:
        lines.append(f"| {sev} | {counts.get(sev, 0)} |")

    lines += ["", "---", "", "## Findings", ""]

    if not findings:
        lines.append("_No vulnerabilities detected._")
    else:
        for i, f in enumerate(findings, 1):
            lines += [
                f"### {i}. {f.get('vulnerability_name', 'Unknown')}",
                "",
                f"| Field | Value |",
                f"|-------|-------|",
                f"| **Severity** | {f.get('severity', 'N/A')} |",
                f"| **Confidence** | {f.get('confidence', 'N/A')} |",
                f"| **CWE** | {f.get('cwe', 'N/A')} |",
                f"| **OWASP** | {f.get('owasp_category', 'N/A')} |",
                f"| **Line** | {f.get('affected_line', 'N/A')} |",
                f"| **Detected By** | {f.get('detection_source', 'N/A')} |",
                "",
                f"**Evidence:**",
                f"```",
                f"{f.get('evidence', '')}",
                f"```",
                "",
                f"**Explanation:**  ",
                f"{f.get('explanation', '')}",
                "",
                f"**Secure Recommendation:**  ",
                f"{f.get('secure_recommendation', '')}",
                "",
                "---",
                "",
            ]

    lines += [
        "## Notes",
        "",
        "- This tool provides **pre-analysis assistance**, not certified audit results.",
        "- **False positives** may occur — review each finding in context.",
        "- **False negatives** are possible — this tool does not guarantee finding all vulnerabilities.",
        "- Consider using this alongside manual code review and penetration testing.",
        "",
        "_Report generated by CodeVuln Agent v1.0.0_",
    ]

    return "\n".join(lines)
